version: '3'

services:
  nginx-rtmp:
    build:
      context: .
    ports:
      - "1935:1935"
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./loop_fallback.sh:/usr/local/bin/loop_fallback.sh
    command: /bin/bash -c "nginx -g 'daemon off;' & /usr/local/bin/loop_fallback.sh"
