version: '3'

services:
  nginx-rtmp:
    build:
      context: .
    ports:
      - "1935:1935"
      - "80:80"
    volumes:
      - ./fallback.sh:/usr/local/bin/fallback.sh
    command: /bin/bash -c "nginx -g 'daemon off;' & /usr/local/bin/fallback.sh"
